{"uuid": "4c0be515-67e2-4773-b459-ab3ef4ed0399", "children": ["bcad65a2-7601-4892-aa50-cae1769ab703"], "befores": [{"name": "_xunit_setup_method_fixture_TestIntroPage", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_TIMED_OUT\n  (Session info: chrome=114.0.5735.134)\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x00B8A813+48355]\n\t(No symbol) [0x00B1C4B1]\n\t(No symbol) [0x00A25358]\n\t(No symbol) [0x00A21B33]\n\t(No symbol) [0x00A18CA5]\n\t(No symbol) [0x00A19D0A]\n\t(No symbol) [0x00A19003]\n\t(No symbol) [0x00A18355]\n\t(No symbol) [0x00A182EC]\n\t(No symbol) [0x00A16F26]\n\t(No symbol) [0x00A17688]\n\t(No symbol) [0x00A26B52]\n\t(No symbol) [0x00A7CF01]\n\t(No symbol) [0x00A6A73C]\n\t(No symbol) [0x00A7C922]\n\t(No symbol) [0x00A6A536]\n\t(No symbol) [0x00A482DC]\n\t(No symbol) [0x00A493DD]\n\tGetHandleVerifier [0x00DEAABD+2539405]\n\tGetHandleVerifier [0x00E2A78F+2800735]\n\tGetHandleVerifier [0x00E2456C+2775612]\n\tGetHandleVerifier [0x00C151E0+616112]\n\t(No symbol) [0x00B25F8C]\n\t(No symbol) [0x00B22328]\n\t(No symbol) [0x00B2240B]\n\t(No symbol) [0x00B14FF7]\n\tBaseThreadInitThunk [0x75910099+25]\n\tRtlGetAppContainerNamedObjectPath [0x77727B6E+286]\n\tRtlGetAppContainerNamedObjectPath [0x77727B3E+238]\n\n", "trace": "  File \"C:\\Users\\evgenyp\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\evgenyp\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\evgenyp\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\evgenyp\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\python.py\", line 907, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"C:\\Users\\evgenyp\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\python.py\", line 787, in _call_with_optional_argument\n    func()\n  File \"C:\\Users\\evgenyp\\Cellenium\\tests\\google\\test_navigation.py\", line 10, in setup\n    self.driver.get_web(web_link='https://nextgenkube.ai-logix.net/interactions', maximize_window=False)\n  File \"C:\\Users\\evgenyp\\Cellenium\\core\\infrastructure\\driver\\engine.py\", line 25, in get_web\n    self.driver.get(web_link)\n  File \"C:\\Users\\evgenyp\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 355, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\evgenyp\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 346, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\evgenyp\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1687089894822, "stop": 1687089939130}], "start": 1687089894822, "stop": 1687089939593}